config/routes.rb
LabMaster::Application.routes.draw do

  root :to => 'home#index'

  resources :group, except: [:show]

  resources :twitter, only: [:index, :show]

  resources :facebook, only: [:index, :show]
  match 'facebook/group/:group_id' => 'facebook#group'

  resources :mail, only: [:index]

  resources :attachment, only: [:index, :show]
  match 'attachment/download/:id' => 'attachment#download'

  resources :blog, except: [:show]

  match 'ajax/search_website' => 'ajax#search_website'

  match 'auth/twitter/callback' => 'sessions#callback'
  match 'auth/facebook/callback' => 'sessions#fb_callback'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/logout' => 'sessions#fb_destroy', :as => :logout

  

end

app/models/group.rb
# -*- coding: utf-8 -*-
# +-------------+-------------+------+-----+---------+----------------+
# | Field       | Type        | Null | Key | Default | Extra          |
# +-------------+-------------+------+-----+---------+----------------+
# | id          | int(11)     | NO   | PRI | NULL    | auto_increment |
# | user_id     | int(11)     | YES  |     | NULL    |                |
# | name        | varchar(30) | YES  |     | NULL    |                |
# | description | text        | YES  |     | NULL    |                |
# | main_flg    | tinyint(1)  | YES  |     | NULL    |                |
# | created_at  | datetime    | NO   |     | NULL    |                |
# | updated_at  | datetime    | NO   |     | NULL    |                |
# +-------------+-------------+------+-----+---------+----------------+

class Group < ActiveRecord::Base
  attr_accessible :name, :description, :main_flg, :user_id, :id
  
  #アソシエーションの定義
  belongs_to :user
  has_many :group_members
  #has_and_belongs_to_many :group_members


  # main_groupsの取得
  def self.main_groups
    main_groups = self.find_all_by_main_flg(true)
  end

  # main_groupかどうか
  def main_group?
    self.main_flg == true
  end

  # 全てのグループIDを配列にして返す
  def self.get_all_group_id
    all_group_id = Array.new
    self.all.each do |group|
      all_group_id << group.id
    end
    return all_group_id
  end

  # 存在するグループIDか否か
  def self.is_group_id?(group_id)
    all_group_id = self.get_all_group_id
    return all_group_id.include?(group_id.to_i) #to_iにしないと、結果が全てfalseになってしまう
  end

end

app/controllers/group_controller.rb
# -*- coding: utf-8 -*-
class GroupController < ApplicationController

  layout "twitter"


  def index
    @groups = Group.all
    #@group_memebres = GroupMember.all
  end

  def new
    @groups = Group.all
    @group = Group.new
  end

  def create
  end

  def edit
    @groups = Group.all
  end

  def update
  end

  def destroy
  end

end

app/helpers/group_helper.rb
module GroupHelper
end

app/views/group/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %>prohibited this group frombeing saved:</h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br />
    <%= f.text_field :group_name %>
  </div>
  <div class="field">
    <%= f.label :group_description %><br />
    <%= f.text_field :group_description %>
  </div>
  <div class="field">
    <%= f.label :selected %><br />
    <%= f.checkbox :selected %>
  </div>
<% end %>

app/views/group/create.html.erb
<h1>Group#create</h1>
<p>Find me in app/views/group/create.html.erb</p>

app/views/group/destroy.html.erb
<h1>Group#destroy</h1>
<p>Find me in app/views/group/destroy.html.erb</p>

app/views/group/edit.html.erb
<%# Group サブナビゲーション %>
<div class="navbar sub_nav">
  <div class='navbar-inner navbar-inner-org'>
    <ul class='nav'>
      <li><%= link_to (raw(t 'sub_nav.allgroups')), group_index_path %></li>
      <li><%= link_to (raw(t 'sub_nav.create_group')), new_group_path %></li>
      <li class='dropdown active_org'>
        <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href='#'><%= raw(t 'sub_nav.edit_group') %><span class="caret" style='vertical-align:baseline;'></span></a>
        <ul id='group_list' class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% @groups.each do |group| %>
            <li><%= link_to group.name, edit_group_path(group) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <div id='typewriter' class='page_desc'>Lab Master内で作られたグループの一覧だよ！ </div>
  </div>
</div>


<div class='contents clearfix'>
  <h1>グループの編集 </h1>
</div>

app/views/group/index.html.erb
<%= stylesheet_link_tag "inside/group", :media => "all" %>

<%# Group サブナビゲーション %>
<div class="navbar sub_nav">
  <div class='navbar-inner navbar-inner-org'>
    <ul class='nav'>
      <li class='active_org'><%= link_to (raw(t 'sub_nav.allgroups')), group_index_path %></li>
      <li><%= link_to (raw(t 'sub_nav.create_group')), new_group_path %></li>
      <li class='dropdown'>
        <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href='#'><%= raw(t 'sub_nav.edit_group') %><span class="caret" style='vertical-align:baseline;'></span></a>
        <ul id='group_list' class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% @groups.each do |group| %>
            <li><%= link_to group.name, edit_group_path(group) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <div id='typewriter' class='page_desc'>Lab Master内で作られたグループの一覧だよ！ </div>
  </div>
</div>

<div class='contents clearfix'>
  <div id='group_list'>
    <div id='lm_title_wrapper' class='clearfix'>
      <div class='lm_group_item lm_group_name'>グループ名</div>
      <div class='lm_group_item lm_group_desc'>グループの説明</div>
      <div class='lm_group_item lm_group_members'>グループのメンバー数</div>
      <div class='lm_group_item lm_group_createdat'>作成日</div>
      <div class='lm_group_item lm_group_owner'>作成者</div>
    </div>
    <% @groups.each do |group| %>
      <div class='lm_group clearfix'>
        <div class='heightLine lm_group_item lm_group_name'><%= group.name %></div>
        <div class='heightLine lm_group_item lm_group_desc'><%= group.description %></div>
        <div class='heightLine lm_group_item lm_group_members'>
        <% members = '' %>
        <% group.group_members.each do |member| %>
          <% members << "#{member.name}<br>" %>
        <% end %>
          <a href='#' rel='tooltip' data-placement='top' title='<%= members %>'>
            <%= "#{group.group_members.count}人" %>
          </a>
        </div>
        <div class='heightLine lm_group_item lm_group_createdat'><%= group.created_at.strftime '%Y-%m-%d %H:%M:%S' %></div>
        <div class='heightLine lm_group_item lm_group_owner'><%= group.user.name %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/group/new.html.erb
<%= javascript_include_tag 'group' %>
<%# Group サブナビゲーション %>
<div class="navbar sub_nav">
  <div class='navbar-inner navbar-inner-org'>
    <ul class='nav'>
      <li><%= link_to (raw(t 'sub_nav.allgroups')), group_index_path %></li>
      <li class='active_org'><%= link_to (raw(t 'sub_nav.create_group')), new_group_path %></li>
      <li class='dropdown'>
        <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href='#'><%= raw(t 'sub_nav.edit_group') %><span class="caret" style='vertical-align:baseline;'></span></a>
        <ul id='group_list' class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% @groups.each do |group| %>
            <li><%= link_to group.name, edit_group_path(group) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <div id='typewriter' class='page_desc'>Lab Master内で作られたグループの一覧だよ！ </div>
  </div>
</div>

<div class='contents clearfix'>
  <h1>グループの新規作成</h1>
</div>

app/views/group/update.html.erb
<h1>Group#update</h1>
<p>Find me in app/views/group/update.html.erb</p>