config/routes.rb
LabMaster::Application.routes.draw do

  root :to => 'home#index'

  resources :group, except: [:show]

  resources :twitter, only: [:index, :show]

  resources :facebook, only: [:index, :show]
  match 'facebook/group/:group_id' => 'facebook#group'

  resources :mail, only: [:index]

  resources :attachment, only: [:index, :show]
  match 'attachment/download/:id' => 'attachment#download'

  resources :blog, except: [:show]

  match 'ajax/search_website' => 'ajax#search_website'

  match 'auth/twitter/callback' => 'sessions#callback'
  match 'auth/facebook/callback' => 'sessions#fb_callback'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/logout' => 'sessions#fb_destroy', :as => :logout

  

end

app/models/blog.rb
# -*- coding: utf-8 -*-
# +------------+--------------+------+-----+---------+----------------+
# | Field      | Type         | Null | Key | Default | Extra          |
# +------------+--------------+------+-----+---------+----------------+
# | id         | int(11)      | NO   | PRI | NULL    | auto_increment |
# | title      | varchar(255) | YES  |     | NULL    |                |
# | summary    | text         | YES  |     | NULL    |                |
# | url        | varchar(200) | YES  | UNI | NULL    |                |
# | author     | varchar(50)  | YES  |     | NULL    |                |
# | image      | varchar(255) | YES  |     | NULL    |                |
# | posted_at  | datetime     | YES  |     | NULL    |                |
# | created_at | datetime     | NO   |     | NULL    |                |
# | updated_at | datetime     | NO   |     | NULL    |                |
# +------------+--------------+------+-----+---------+----------------+
# registerd_blog_idを追加する必要がある
class Blog < ActiveRecord::Base
  attr_accessible :title, :summary, :url, :author, :image, :posted_at

  belongs_to :registered_blog
  scope :new, order('posted_at DESC')
  scope :old, order('posted_at ASC')
  scope :top50, limit(50)
  scope :top30, limit(30)
  scope :top100, limit(100)

  # Kaminari(ページネーション)の設定。1ページに表示する件数
  paginates_per 20

  # エントリを日付ごとに集計する
  def self.list_up_blog_entry_by_date
    #select DATE_FORMAT(posted_at, '%Y%m') as date from blogs group by date;
    self.find_by_sql("select DATE_FORMAT(posted_at, '%Y%m') as entry_date, count(*) as counter from blogs group by entry_date;")
  end


  # 条件(パラメータ）を元にエントリの検索をし、取得する
  def self.search_entry_with_params(opt)
    # パラメータに検索クエリがある場合
    if opt['q']
      entries = self.search_entries_by_query(opt['q'], opt['sort'])
    # パラメータにタイトル指定がある場合
    elsif opt['blog_id']
      entries = self.search_entries_by_blog_id(opt['blog_id'], opt['sort'])
    else
      entries = self.search_entries(opt['sort'])
    end

    return entries
  end


  def self.search_entries_by_query(query, sort)
    if sort == 'asc'
      entries = self.where('title LIKE ? or summary LIKE ?', "%#{query}%", "%#{query}%").old
    else
      entries = self.where('title LIKE ? or summary LIKE ?', "%#{query}%", "%#{query}%").new
    end
    return entries
  end


  def self.search_entries_by_blog_id(blog_id, sort)
    if sort == 'asc'
      entries = self.where('registered_blog_id = ?', "#{blog_id}").old
    else
      entries = self.where('registered_blog_id = ?', "#{blog_id}" ).new
    end
    return entries
  end


  def self.search_entries(sort)
    if sort == 'asc'
      entries = self.old
    else
      entries = self.new
    end
    return entries
  end

end

app/controllers/blog_controller.rb
# -*- coding: utf-8 -*-
class BlogController < ApplicationController
  layout "twitter"
  before_filter :is_admin, :only => ['new','create','edit','update','destroy']

  def index
    # URLパラメータの取得
    search_options = params
    @blogs = Blog.search_entry_with_params(search_options).page params[:page]
    #@blogs = Blog.order('posted_at DESC').limit(30).page params[:page]

    # 日付
    @entry_date = Blog.list_up_blog_entry_by_date

    # RSS登録されているブログ 
    @registered_blogs = RegisteredBlog.all
  end

  def new
    @blog = RegisteredBlog.new
    @registered_blogs = RegisteredBlog.all
  end

  def create
    @blog = RegisteredBlog.new
    @blog.title = params[:registered_blog][:title]
    @blog.url = params[:registered_blog][:url]
    @blog.feed_url = params[:registered_blog][:feed_url]
    @blog.twitter_id = session[:twitter_id]
    @blog.crawl_flg = true 

    if @blog.save
      redirect_to(new_blog_path, alert: "新しいブログの登録が完了しました！")
    else
      redirect_to(new_blog_path.errors, status: "unprocessable_entity")
    end
  end

  def edit
    @blog = RegisteredBlog.find(params[:id])
    @registered_blogs = RegisteredBlog.all
  end

  def update
    @blog = RegisteredBlog.find(params[:id])
    if @blog.update_attributes(params[:registered_blog])
      redirect_to edit_blog_path(params[:id], alert: "ブログの編集が完了しました！")
    else
      redirect_to edit_blog_path(params[:id], alert: "ブログの編集に失敗しました。もう一度やり直してください。")
    end
  end

  def destroy
    @blog = RegisteredBlog.find(params[:id])
    @blog.destroy

    redirect_to blog_index_path
  end

  private

  def is_admin
    unless session[:twitter_id] == 154423524
      redirect_to blog_index_path
    end
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<%= stylesheet_link_tag "inside/blog", :media => "all" %>
<%= javascript_include_tag "inside/blog", :media => "all" %>
<%# Blog サブナビゲーション %>
<div class="navbar sub_nav">
  <div class='navbar-inner navbar-inner-org'>
    <ul class='nav'>
      <li><%= link_to (raw(t 'sub_nav.blogs')), blog_index_path %></li>
      <li><%= link_to (raw(t 'sub_nav.new_blog')), new_blog_path %></li>
      <li class='dropdown active_org'>
        <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href='#'><%= raw(t 'sub_nav.edit_blog') %><span class="caret" style='vertical-align:baseline;'></span></a>
        <ul id='group_list' class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% @registered_blogs.each do |blog| %>
            <li><%= link_to blog.title, edit_blog_path(blog) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <div id='typewriter' class='page_desc'>実験中</div>
  </div>
</div>

<div class='contents clearfix'>
  <script>
    var message = "<%= flash[:alert] %>";
    if(message){alert(message);}
  </script>
  <h1>登録したブログの編集</h1>
  <%= form_for(@blog, url: blog_path(@blog.id)) do |blog| %>
    <%= blog.label :url %>
    <%= blog.url_field :url, maxlength: 195, required: true, id: 'result_url' %>

    <%= blog.label :title %>
    <%= blog.text_field :title, maxlength: 250, required: true, id: 'result_title' %>

    <%= blog.label :feed_url %>
    <%= blog.url_field :feed_url, maxlength: 195, required: true, id: 'result_feedurl' %>

    <br>

    <%= blog.submit "修正する", id: 'submit_button' %>
    <button><%= link_to "削除する", blog_path(@blog.id), method: 'delete', confirm: "「#{@blog.title}」を削除します。よろしいですか？" %></button>
  <% end %>
</div>

app/views/blog/index.html.erb
<%= stylesheet_link_tag "inside/blog", :media => "all" %>
<%= stylesheet_link_tag "inside/mail", :media => "all" %>
<%= javascript_include_tag "inside/blog", :media => "all" %>

<%# Blog サブナビゲーション %>
<div class="navbar sub_nav">
  <div class='navbar-inner navbar-inner-org'>
    <ul class='nav'>
      <li class='active_org'><%= link_to (raw(t 'sub_nav.blogs')), blog_index_path %></li>
      <% if session[:twitter_id] == 154423524 %>
      <li><%= link_to (raw(t 'sub_nav.new_blog')), new_blog_path %></li>
      <li class='dropdown'>
        <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href='#'><%= raw(t 'sub_nav.edit_blog') %><span class="caret" style='vertical-align:baseline;'></span></a>
        <ul id='group_list' class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% @registered_blogs.each do |blog| %>
            <li><%= link_to blog.title, edit_blog_path(blog) %></li>
          <% end %>
        </ul>
      </li>
      <% end %>
      <li>
        <div class='input-append subnav_search'>
          <%= form_tag(blog_index_path, method: 'GET') do %>
            <%= text_field_tag 'q', '', id: 'entry_search', placeholder: 'Search...' %>
            <span class="add-on" style='margin-top:10px;margin-right:15px;'><i class='icon-search'></i></span>
          <% end %>
        </div>
      </li>
    </ul>
    <div id='typewriter' class='page_desc'>現在、試験的にいくつかのブログやサイトを取得対象にしています </div>
  </div>
</div>

<div class='contents clearfix'>
  <%#-------------------------------------------------------LEFT---------------------------------------------------------------%>
  <div class='blog_list'>
    <div class='blog_list_inner clearfix'>

    <%#-----SEARCH OPTION------%>
    <div id='search_option_wrapper'>
      <div class='search_option clearfix'>
        <%#--sort---%>
        <div class='sort_box clearfix left'>
          <div class='clearfix'>
            <div class='left text_white'>ソート：</div>
            <div class='left'>
              <%= link_to(raw("<span class='label #{params[:sort] == 'asc' ? 'label-default' : 'label-warning'}'>新 → 古</span>"), params.merge(opt={sort: 'desc'})) %> 
              <%= link_to(raw("<span class='label #{params[:sort] == 'asc' ? 'label-warning' : 'label-default'}'>古 → 新</span>"), params.merge(opt={sort: 'asc'})) %> 
            </div>
          </div>
        </div>
        <%#--sender---%>
        <div class='sender_box left'>
          <form>
            <select id='select_sender' class='text_small' style='margin:0;padding:0;'>
              <option>ブログタイトルで絞り込む</option>
              <% @registered_blogs.each do |blog| %>
                <a href='#'><option value='<%= blog.id %>'><%= blog.title %></option></a>
              <% end %>
            </select>
          </form>
        </div>
      </div>
    </div><!-- div#search_option_wrapper -->

      <% if @blogs.present? %>
        <% if false %>
          <div class='counter'>
            該当エントリ：全<span class='big_text text_red bold'> 100 </span>件
          </div>
        <% end %>
        <% @blogs.each do |blog| %>
          <article class='blog'>
            <header class='blog_title'>
              <h2><%= link_to blog.title, blog.url %></h2>
            </header>
            <p class='blog_summary'><%= raw blog.summary %></p>
            <div class='blog_postedat'><%= blog.posted_at.strftime '%Y-%m-%d %H:%M:%S' %></div>
          </article>
        <% end %>
      <% else %>
        <div class='no_blog' style='line-height:30px;text-align:center;'>
          <span class='text_red'><i class='icon-warning-sign text_red'></i> <%= t 'blog_not_found' %></span>
        </div>
      <% end %>
    </div>
    <% # ページネーション %>
    <div class='center_text'>
      <%= paginate @blogs %>
    </div>
  </div>

  <%#-------------------------------------------------------RIGHT---------------------------------------------------------------%>
  <div class='blog_meta'>
    <% #登録しているブログの一覧 %>
    <section class='rss_list'>
      <header class='rss_list_title'>登録しているブログ一覧</header>
      <div class='rss_list_body'>
        <ul class='unstyled'>
          <% @registered_blogs.each do |blog| %>
            <% if session[:twitter_id] == 154423524 %>
              <li><%= link_to blog.title, edit_blog_path(blog)%></li>
            <% else %>
              <li><%= blog.title %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </section>

    <% #各ブログでのエントリを日付ごとに集計する %>
    <section class='rss_list'>
      <header class='rss_list_title'>日付での集計</header>
      <div class='rss_list_body'>
        <ul class='unstyled'>
          <% @entry_date.each do |entry| %>
            <li><%= "#{entry.entry_date}(#{entry.counter})" %></li>
          <% end %>
        </ul>
      </div>
    </section>
  </div>
</div>

app/views/blog/new.html.erb
<%= stylesheet_link_tag "inside/blog", :media => "all" %>
<%= javascript_include_tag "inside/blog", :media => "all" %>

<%# Blog サブナビゲーション %>
<div class="navbar sub_nav">
  <div class='navbar-inner navbar-inner-org'>
    <ul class='nav'>
      <li><%= link_to (raw(t 'sub_nav.blogs')), blog_index_path %></li>
      <li class='active_org'><%= link_to (raw(t 'sub_nav.new_blog')), new_blog_path %></li>
      <li class='dropdown'>
        <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href='#'><%= raw(t 'sub_nav.edit_blog') %><span class="caret" style='vertical-align:baseline;'></span></a>
        <ul id='group_list' class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% @registered_blogs.each do |blog| %>
            <li><%= link_to blog.title, edit_blog_path(blog) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    <div id='typewriter' class='page_desc'>実験中</div>
  </div>
</div>

<div class='contents clearfix'>
  <script>
    var message = "<%= flash[:alert] %>";
    if(message){alert(message);}
  </script>
  <h1>ブログの新規登録</h1>
  <%= form_tag(ajax_search_website_path, remote: true) do %>
    <%= url_field_tag :url %>
    <%= submit_tag "検索", id:'websearch' %>
    <span id='progress'></span>
  <% end %>
  <div id='errormes'></div>
  

  <%= form_for(@blog, url: blog_index_path, :html => {:method => 'post'}) do |blog| %>
    <%= blog.label :title %>
    <%= blog.text_field :title, maxlength: 250, required: true, id: 'result_title' %>

    <%= blog.label :feed_url %>
    <%= blog.url_field :feed_url, maxlength: 195, required: true, id: 'result_feedurl' %>

    <%= blog.hidden_field :url, maxlength: 195, required: true, id: 'result_url' %>
    <br>
    <%= blog.submit "登録する", id: 'submit_button' %>
  <% end %>
</div>

app/views/blog/show.html.erb
fuga