config/routes.rb
LabMaster::Application.routes.draw do

  root :to => 'home#index'

  resources :group, except: [:show]

  resources :twitter, only: [:index, :show]

  resources :facebook, only: [:index, :show]
  match 'facebook/group/:group_id' => 'facebook#group'

  resources :mail, only: [:index]

  resources :attachment, only: [:index, :show]
  match 'attachment/download/:id' => 'attachment#download'

  resources :blog, except: [:show]

  match 'ajax/search_website' => 'ajax#search_website'

  match 'auth/twitter/callback' => 'sessions#callback'
  match 'auth/facebook/callback' => 'sessions#fb_callback'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/logout' => 'sessions#fb_destroy', :as => :logout

  

end

app/views/layouts/_footer.html.erb
<div id="footer">
</div>

app/views/layouts/_header.html.erb
<div id='header' class='clearfix'>
  <div id='header_inner' class='clearfix'>
    <div id='logo'>
      <%= link_to "Lab Master", root_path, class: "brand", id: "logo" %>
    </div>
    <div id='navigation_menu'>
      <div id='contents_menu'>
        <ul class='clearfix' style='margin:0;'>
          <li><%= link_to (raw(t "nav.facebook")), facebook_index_path, class: 'nav_item' %></li>
          <li><%= link_to (raw(t "nav.twitter")), twitter_index_path, class: 'nav_item' %></li>
          <li><%= link_to (raw(t "nav.mail")), mail_index_path, class: 'nav_item' %></li>
          <li><%= link_to (raw(t "nav.file")), attachment_index_path, class: 'nav_item' %></li>
          <li><%= link_to (raw(t "nav.blog")), blog_index_path, class: 'nav_item' %></li>
          <li><%= link_to (raw(t "nav.group")), group_index_path, class: 'nav_item' %></li>
        </ul>
      </div>
      <div id ='user_menu'>
        <ul class='pull-right' data-dropdown='dropdown'> 
          <!-- login -->
          <% if logged_in? %>
            <li class="dropdown" id="menu1">
              <a href="#menu1" class="dropdown-toggle" data-toggle="dropdown" data-target="#" style='color:#ccc;'>
                <%= image_tag "#{current_user.image_url}", class: "topBarIcon", width:"30", height:"30" %>
                <%= raw(" #{current_user.screen_name} <b class='caret' style='vertical-align:baseline;'></b>") %>
              </a>
              <ul class="dropdown-menu" id='user_menu_list' style='min-width:120px;'>
                <li>
                  <%= link_to 'logout', logout_path %>
                </li>
              </ul>
            </li>
          <% else %>
            <% #未ログイン %>
            <li> 
              <%= link_to image_tag('sign-in-with-twitter-gray.png'), "auth/twitter", id: 'login_link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<% if false %>
<% #TOPバー 移動式 %>
<!--
<div class="navbar navbar-inverse navbar-static-top">
  <div id="global_nav" class="navbar-inner">
    <div class="container">
      <%= link_to "Lab Master", root_path, class: "brand", id: "logo" %>
      <div class="nav-collapse collapse">

        <ul class="nav">
          <li><%= link_to (raw(t "nav.facebook")), facebook_index_path %></li>
          <li><%= link_to (raw(t "nav.twitter")), twitter_index_path %></li>
          <li><%= link_to (raw(t "nav.mail")), mail_index_path %></li>
          <li><%= link_to (raw(t "nav.file")), attachment_index_path %></li>
          <li><%= link_to (raw(t "nav.blog")), "#" %></li>
          <li><%= link_to (raw(t "nav.group")), group_index_path %></li>
        </ul>
        <ul class="nav pull-right" data-dropdown="dropdown"> 
          <!-- login -->
          <% if logged_in? %>
            <li class="dropdown" id="menu1">
              <a href="#menu1" class="dropdown-toggle" data-toggle="dropdown" data-target="#">
                <%= image_tag "#{current_user.image_url}", class: "topBarIcon", width:"30", height:"30" %>
                <%= raw(" #{current_user.screen_name} <b class='caret' style='vertical-align:baseline;'></b>") %>
              </a>
            <ul class="dropdown-menu">
              <li>
              <%= link_to 'logout', logout_path %>
              </li>
            </ul>
            </li>
          <% else %>
            <% #未ログイン %>
            <li> 
            <%= link_to "ログイン", "auth/twitter" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
-->
<% end %>
<% if false %>
  <% if fb_logged_in? -%>
    <%= link_to 'logout', logout_path %>
  <% else %>
    <%= link_to "Facebookでログイン", "auth/facebook" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Lab Master</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35642967-1']);
    _gaq.push(['_trackPageview']);

    (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();
  </script>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/twitter.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Lab Master</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css" rel="stylesheet" />
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35642967-1']);
    _gaq.push(['_trackPageview']);

    (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();
  </script>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="app_container">
    <div id="main_contents">
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>